//
// Accountlist.swift
//
// Generated by JSONSwiftExporter on Mar 08, 2023
//

import Foundation

public struct Accountlist: Codable {

    let paymentStatus: String
    let currency: String
    let typeEN: String
    let bankId: String?
    let multibankingAccount: Bool
    let balance: Double
    let iban: String
    let logoUrl: String?
    let accountId: String
    let bankName: String
    let billPaymentAllowed: String
    let workingbalance: Double
    let typeBG: String
    let tdSetup: String
}

    

extension Accountlist {

        public func fetchAccountlist(jsonString: String) -> Accountlist {
            let decoder = JSONDecoder()
            let jsonData = jsonString.data(using: .utf8)!
            
            let parseJson: Accountlist = try! decoder.decode(Accountlist.self, from: jsonData)
            return parseJson
        }

    }

